// Mirrors backend/src/config/constants.js ROLES — kept as plain strings
// (not shared code) since frontend and backend are separate packages.
export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  FINANCE_ADMIN: 'FINANCE_ADMIN',
  VERIFICATION_ADMIN: 'VERIFICATION_ADMIN',
  SUPPORT_ADMIN: 'SUPPORT_ADMIN',
  CONTENT_ADMIN: 'CONTENT_ADMIN',
  OPERATIONS_ADMIN: 'OPERATIONS_ADMIN',
  JOB_SEEKER: 'JOB_SEEKER',
  EMPLOYER: 'EMPLOYER',
  FREELANCER: 'FREELANCER',
  TRAINER: 'TRAINER',
  MANPOWER_VENDOR: 'MANPOWER_VENDOR',
};

export const ADMIN_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.FINANCE_ADMIN,
  ROLES.VERIFICATION_ADMIN,
  ROLES.SUPPORT_ADMIN,
  ROLES.CONTENT_ADMIN,
  ROLES.OPERATIONS_ADMIN,
];
